site_name: Project Sol

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-1
        name: Switch to dark mode
      primary: Deep Orange
      accent: Deep Orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
      primary: Black
      accent: Deep Orange

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  logo: logos/logo_white.svg
  favicon: logos/logo_deeporange.svg

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

  - toc:
      permalink: true

extra:
  generator: false

copyright: Proudly Open Source 
repo_url: https://github.com/javier-solis/notes

extra_css:
  - stylesheets/extra.css